[/Admin/CreateUser]
CreateUserResource = /admin/CreateUserResource.php

[/Admin/DeleteUser]
DeleteUserResource = /admin/DeleteUserResource.php

[/Admin/GetUsers]
GetUsersResource = /admin/GetUsersResource.php

[/Admin/SearchLdap]
SearchLdapResource = /admin/SearchLdapResource.php

[/Admin/RenameUser]
RenameUserResource = /admin/RenameUserResource.php

[/Admin/UpdateUser]
UpdateUserResource = /admin/UpdateUserResource.php

[/AvailableServers]
AvailableServersResource = /availableServers/AvailableServersResource.php

[/ExpressoVersion]
ExpressoVersionResource = /core/ExpressoVersionResource.php

[/Login]
LoginResource = /core/LoginResource.php

[/Logout]
LogoutResource = /core/LogoutResource.php

[/Mail/Folders]
FoldersResource = /mail/FoldersResource.php

[/Mail/RenameFolder]
RenameFolderResource = /mail/RenameFolderResource.php

[/Mail/AddFolder]
AddFolderResource = /mail/AddFolderResource.php

[/Mail/DelFolder]
DelFolderResource = /mail/DelFolderResource.php

[/Mail/DelMessage]
DelMessageResource = /mail/DelMessageResource.php

[/Mail/Messages]
MessagesResource = /mail/MessagesResource.php

[/Mail/CleanTrash]
CleanTrashResource = /mail/CleanTrashResource.php

[/Mail/Send]
SendResource = /mail/SendResource.php

[/Mail/SendSupportFeedback]
SendSupportFeedbackResource = /mail/SendSupportFeedbackResource.php

[/Mail/Attachment]
AttachmentResource = /mail/AttachmentResource.php

[/Preferences/ChangePassword]
ChangePasswordResource = /preferences/ChangePasswordResource.php

[/Preferences/UserPreferences]
UserPreferencesResource = /preferences/UserPreferencesResource.php

[/Preferences/ChangeUserPreferences]
ChangeUserPreferencesResource = /preferences/ChangeUserPreferencesResource.php

[/Catalog/Contacts]
ContactsResource = /catalog/ContactsResource.php

[/Catalog/ContactAdd]
ContactAddResource = /catalog/ContactAddResource.php

[/Catalog/ContactDelete]
ContactDeleteResource = /catalog/ContactDeleteResource.php

[/Catalog/ContactPicture]
ContactPictureResource = /catalog/ContactPictureResource.php

[/Calendar/Events]
EventsResource = /calendar/EventsResource.php

[/Calendar/Event]
EventResource = /calendar/EventResource.php

[/Calendar/AddEvent]
AddEventResource = /calendar/AddEventResource.php

[/Calendar/DelEvent]
DelEventResource = /calendar/DelEventResource.php

[/Calendar/EventCategories]
EventCategoriesResource = /calendar/EventCategoriesResource.php

[/SMS/InfoPersonal]
InfoPersonalResource = /sms/InfoPersonalResource.php

[/SMS/SendCheckCode]
SendCheckCodeResource = /sms/SendCheckCodeResource.php

[/SMS/SendMessage]
SendMessageResource = /sms/SendMessageResource.php

[/SMS/SubmitPersonalForm]
SubmitPersonalFormResource = /sms/SubmitPersonalFormResource.php
