[/Documentation]
DocumentationResource = /core/DocumentationResource.php

- OK - [/ExpressoVersion]
ExpressoVersionResource = /core/ExpressoVersionResource.php

[/ExpressoBanner]
ExpressoBannerResource = /core/ExpressoBannerResource.php

- OK - [/Login]
LoginResource = /core/LoginResource.php

- OK - [/Logout]
LogoutResource = /core/LogoutResource.php

- OK - [/UserApps]
UserAppsResource = /core/UserAppsResource.php

- A FAZER [/UserApi]
UserApiResource = /core/UserApiResource.php

- OK - [/Mail/Folders]
FoldersResource = /mail/FoldersResource.php

- OK - [/Mail/RenameFolder]
RenameFolderResource = /mail/RenameFolderResource.php

- OK - [/Mail/AddFolder]
AddFolderResource = /mail/AddFolderResource.php

- REVISAR [/Mail/DelFolder]
DelFolderResource = /mail/DelFolderResource.php

- OK - [/Mail/FlagMessage]
FlagMessageResource = /mail/FlagMessageResource.php

- OK - [/Mail/DelMessage]
DelMessageResource = /mail/DelMessageResource.php

- OK - [/Mail/Messages]
MessagesResource = /mail/MessagesResource.php

- OK - [/Mail/MoveMessages]
MoveMessagesResource = /mail/MoveMessagesResource.php

- OK - [/Mail/CleanTrash]
CleanTrashResource = /mail/CleanTrashResource.php

- REVISAR - [/Mail/Send]
SendResource = /mail/SendResource.php

- REVISAR - [/Mail/SpamMessage]
SpamMessageResource = /mail/SpamMessageResource.php

- REVISAR - [/Mail/SendSupportFeedback]
SendSupportFeedbackResource = /mail/SendSupportFeedbackResource.php

- REVISAR - [/Mail/Attachment]
AttachmentResource = /mail/AttachmentResource.php



- OK - [/Preferences/ChangePassword]
ChangePasswordResource = /preferences/ChangePasswordResource.php

- OK - [/Preferences/UserPreferences]
UserPreferencesResource = /preferences/UserPreferencesResource.php

- OK - [/Preferences/ChangeUserPreferences]
ChangeUserPreferencesResource = /preferences/ChangeUserPreferencesResource.php

- OK - [/Catalog/Contacts]
ContactsResource = /catalog/ContactsResource.php

- OK - [/Catalog/ContactAdd]
ContactAddResource = /catalog/ContactAddResource.php

- OK - [/Catalog/ContactDelete]
ContactDeleteResource = /catalog/ContactDeleteResource.php

- OK - [/Catalog/ContactPicture]
ContactPictureResource = /catalog/ContactPictureResource.php

- OK - [/Catalog/Photo(/.*)?]
ContactEmailPhotoResource = /catalog/ContactEmailPhotoResource.php



 - OK - [/Calendar/Events]
EventsResource = /calendar/EventsResource.php

- OK - [/Calendar/Event]
EventResource = /calendar/EventResource.php

- REVISAR - [/Calendar/AddEvent]
AddEventResource = /calendar/AddEventResource.php

- REVISAR - [/Calendar/DelEvent]
DelEventResource = /calendar/DelEventResource.php

- REVISAR - [/Calendar/EventCategories]
EventCategoriesResource = /calendar/EventCategoriesResource.php


- REVISAR - [/Services/Chat]
ChatResource = /services/ChatResource.php


[/SMS/InfoPersonal]
InfoPersonalResource = /sms/InfoPersonalResource.php

[/SMS/SendCheckCode]
SendCheckCodeResource = /sms/SendCheckCodeResource.php

[/SMS/SendMessage]
SendMessageResource = /sms/SendMessageResource.php

[/SMS/SubmitPersonalForm]
SubmitPersonalFormResource = /sms/SubmitPersonalFormResource.php



[/Admin/CreateUser]
CreateUserResource = /admin/CreateUserResource.php

[/Admin/DeleteUser]
DeleteUserResource = /admin/DeleteUserResource.php

[/Admin/GetUsers]
GetUsersResource = /admin/GetUsersResource.php

[/Admin/SearchLdap]
SearchLdapResource = /admin/SearchLdapResource.php

[/Admin/RenameUser]
RenameUserResource = /admin/RenameUserResource.php

[/Admin/UpdateUser]
UpdateUserResource = /admin/UpdateUserResource.php
